baseurl = "/"
languageCode = "en-us"
title = "Ahmad Sufyan"
theme = "zero"
[params]
   Description = "Perjalanan Belajar"
[permalinks]
   catatan = ":slug"
   code = ":slug"
   linux = ":slug"

# Google Analytics
googleAnalytics = "UA-163996782-1"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4