baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "id"
title = "Kotlin enthusiast"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-163996782-1"

[params]
title = "I'm Ahmad Sufyan"
author = "Ahmad Sufyan"
description = "All about my knowledge"
profilePicture = "uploads/fyan.jpg"
keywords = "Ahmad Sufyan"
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCw-os_0NNQy-4y-z4qCEPSA"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/ahmadsufyan455"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/fyann__/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Coretan"
  weight = 200
  identifier = "coretan"
  url = "/categories/coretan/"

  [[menu.main]]
  name = "Code"
  weight = 200
  identifier = "code"
  url = "/categories/code/"