baseURL = "/"
title = "Ahmad Sufyan"
theme = "hugo-notepadium"
copyright = "©2020 Ahmad Sufyan"

languageCode = "en-us"
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

#Google Analytics
googleAnalytics = "UA-163996782-1"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = "All About My Knowledge"
license = ""  # CC License

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/

# custom navigation items

[[params.nav.custom]]
title = "Code"
url = "/categories/code"

[[params.nav.custom]]
title = "Github"
url = "https://github.com/ahmadsufyan455"